"""Init

Revision ID: 338117e8a6f7
Revises: 
Create Date: 2026-02-21 22:51:47.884145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338117e8a6f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('role_details', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('role_details')
        batch_op.drop_column('role')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
